/* Botones de traducción */
let espanol = document.getElementById("espanol");
let english = document.getElementById("english");
/* Elementos a traduccir */
let tituloprimero = document.getElementById("titulop");
let titulodos = document.getElementById("titulo2");
let tituloproductos = document.getElementById("tituloproductos");
let descripcionproductos = document.getElementById("descripcionp");
let botoncatalogo = document.getElementById("btnc");
let botoncita = document.getElementById("btncita");
let titulocapilar = document.getElementById("titulocapilar");
let listcapilar1 = document.getElementById("listc1");
let listcapilar2 = document.getElementById("listc2");
let listcapilar3 = document.getElementById("listc3");
let listcapilarc4 = document.getElementById("listc4");
let listcapilar5 = document.getElementById("listc5");
let listcapilar6 = document.getElementById("listc6");
let listcapilar7 = document.getElementById("listc7");
let listcapilar8 = document.getElementById("listc8");
let listcapilar9 = document.getElementById("listc9");
let listcapilar10 = document.getElementById("listc10");
let listcapilar11 = document.getElementById("listc11");
let listcapilar12 = document.getElementById("listc12");
let listcapilar13 = document.getElementById("listc13");
let listcapilar14 = document.getElementById("listc14");
let listcapilar15 = document.getElementById("listc15");
let titulocorporal = document.getElementById("titulocorporal");
let listcorporal1 = document.getElementById("listcorporal1");
let listcorporal2 = document.getElementById("listcorporal2");
let listcorporal3 = document.getElementById("listcorporal3");
let listcorporal4 = document.getElementById("listcorporal4");
let listcorporal5 = document.getElementById("listcorporal5");
let listcorporal6 = document.getElementById("listcorporal6");
let titulofacial = document.getElementById("titulofacial");
let listfacial1 = document.getElementById("listfacial1");
let listfacial2 = document.getElementById("listfacial2");
let listfacial3 = document.getElementById("listfacial3");
let listfacial4 = document.getElementById("listfacial4");
let listfacial5 = document.getElementById("listfacial5");
let listfacial6 = document.getElementById("listfacial6");
let textoregistro = document.getElementById("textoregistro");
let parraforegistro = document.getElementById("parraforegistro");
let btncatalogor = document.getElementById("btncatalogo");
let textocuenta = document.getElementById("textocuenta");
let btniniciar = document.getElementById("btniniciar");
let btnregistrate = document.getElementById("btnregistrate");
let tituloslider1 = document.getElementById("tituloslider1");
let parrafoslider1 = document.getElementById("parrafoslider1");
let tituloslider2 = document.getElementById("tituloslider2");
let parrafoslider2 = document.getElementById("parrafoslider2");
let tituloslider3 = document.getElementById("tituloslider3");
let parrafoslider3 = document.getElementById("parrafoslider3");
let titulodesarrollo = document.getElementById("titulodesarrollo");
let tituloformula = document.getElementById("tituloformula");
let list1 = document.getElementById("list1");
let list2 = document.getElementById("list2");
let list3 = document.getElementById("list3");
let list4 = document.getElementById("list4");
let list5 = document.getElementById("list5");
let list6 = document.getElementById("list6");
let icono1 = document.getElementById("icono1");
let icono2 = document.getElementById("icono2");
let icono3 = document.getElementById("icono3");
let icono4 = document.getElementById("icono4");
/* Eventos de click para cambiar idioma */
espanol.onclick = ()=>{
    setLanguage("espanol");
    localStorage.setItem("Lang","espanol");
};
english.onclick = ()=>{
    setLanguage("english");
    localStorage.setItem("Lang","english");
};
onload = ()=>{
    setLanguage(localStorage.getItem("Lang"));
};
/* Traducciones */
function setLanguage(getLanguage){
  if(getLanguage === "espanol"){
    titulop.innerHTML = "Inicia tu marca aquí!";
    titulo2.innerHTML = "LABORATORIO COSMÉTICO CON ESTÁNDARES DE CALIDAD INTERNACIONALES";
    tituloproductos.innerHTML = "Amplio";
    descripcionp.innerHTML = "Portafolio de productos y presentaciones";
    btnc.innerHTML = "Ver en catalogo";
    btncita.innerHTML = "AGENDA UNA CITA";
    titulocapilar.innerHTML = "CAPILAR";
    listc1.innerHTML = "Shampoos";
    listc2.innerHTML = "Acondicionador";
    listc3.innerHTML = "Tratamientos";
    listc4.innerHTML = "Mascarillas";
    listc5.innerHTML = "Oleos";
    listc6.innerHTML = "Serums";
    listc7.innerHTML = "Aceites";
    listc8.innerHTML = "Tónicos";
    listc9.innerHTML = "Gel";
    listc10.innerHTML = "Spray fijador";
    listc11.innerHTML = "Keratina";
    listc12.innerHTML = "Botox";
    listc13.innerHTML = "Repolarizador";
    listc14.innerHTML = "Crema para peinar";
    listc15.innerHTML = "Crema de peinar";
    titulocorporal.innerHTML = "CORPORAL";
    listcorporal1.innerHTML = "Cremas";
    listcorporal2.innerHTML = "Geles";
    listcorporal3.innerHTML = "Aceites";
    listcorporal4.innerHTML = "Exfoliantes";
    listcorporal5.innerHTML = "Jabones";
    listcorporal6innerHTML = "Loción";
    titulofacial.innerHTML = "FACIAL";
    listfacial1.innerHTML = "Cremas";
    listfacial2.innerHTML = "Geles";
    listfacial3.innerHTML = "Espumas";
    listfacial4.innerHTML = "Tónico";
    listfacial5.innerHTML = "Jabones";
    listfacial6.innerHTML = "Aceites";
    textoregistro.innerHTML = "EMPIEZA TU PROCESO";
    parraforegistro.innerHTML = "Lorem ipsum dolor sit amet consectetur.";
    btncatalogo.innerHTML = "ver Catalogo";
    textocuenta.innerHTML = "¿Tienes una cuenta? Inicia sesión aquí";
    btniniciar.innerHTML = "Iniciar sesion";
    btnregistrate.innerHTML = "Quiero registrarme por otro medio";
    tituloslider1.innerHTML = "slide 1";
    parrafoslider1.innerHTML = "Lorem ipsum dolor sit amet consectetur.";
    tituloslider2.innerHTML = "slide 2";
    parrafoslider2.innerHTML = "Lorem ipsum dolor sit amet consectetur.";
    tituloslider3.innerHTML = "slide 3";
    parrafoslider3.innerHTML = "Lorem ipsum dolor sit amet consectetur.";
    titulodesarrollo.innerHTML = "DESARROLLO";
    tituloformula.innerHTML = "de Fórmulas";
    list1.innerHTML = "Con extractos naturales";
    list2.innerHTML = "No testeadas en animales";
    list3.innerHTML = "Veganas";
    list4innerHTML = "Sin sulfatos";
    list5.innerHTML = "Sin parabenos";
    list6.innerHTML = "Sin sal";
    icono1.innerHTML = "Garantia de Tiempos de Entrega";
    icono2.innerHTML = "Versatilidad en las cantidades deseadas";
    icono3.innerHTML = "Garantia en el desempeño de productos";
    icono4.innerHTML = "Garantía en el desempeño de productos";
    }else if(getLanguage ==="english"){
        titulop.innerHTML = "START YOUR LABEL NOW!";
        titulo2.innerHTML = "COSMETIC LABORATORY WITH INTERNATIONAL QUALITY STANDARDS";
        tituloproductos.innerHTML = "Large";
        descripcionp.innerHTML = "Wide Portfolio";
        btnc.innerHTML = "See in catalog";
        btncita.innerHTML = "APPOINTMENT";
        titulocapilar.innerHTML = "CAPILLARY";
        listc1.innerHTML = "Shampoos";
        listc2.innerHTML = "Conditioner";
        listc3.innerHTML = "Treatments";
        listc4.innerHTML = "Masks";
        listc5.innerHTML = "Oils";
        listc6.innerHTML = "Serums";
        listc7.innerHTML = "Oils";
        listc8.innerHTML = "Tonics";
        listc9.innerHTML = "Gel";
        listc10.innerHTML = "fixing spray";
        listc11.innerHTML = "Keratin";
        listc12.innerHTML = "Botox";
        listc13.innerHTML = "Repolarizer";
        listc14.innerHTML = "Styling cream";
        listc15.innerHTML = "Lotion";
        titulocorporal.innerHTML = "BODY";
        listcorporal1.innerHTML = "Creams";
        listcorporal2.innerHTML = "Gels";
        listcorporal3.innerHTML = "Oils";
        listcorporal4.innerHTML = "Exfoliants";
        listcorporal5.innerHTML = "Soaps";
        listcorporal6innerHTML = "Lotion";
        titulofacial.innerHTML = "FACE";
        listfacial1.innerHTML = "Creams";
        listfacial2.innerHTML = "Gels";
        listfacial3.innerHTML = "Foams";
        listfacial4.innerHTML = "Tonic";
        listfacial5.innerHTML = "Soaps";
        listfacial6.innerHTML = "Oils";
        textoregistro.innerHTML = " Why work with us?";
        parraforegistro.innerHTML = "Lorem ipsum dolor sit amet consectetur.";
        btncatalogo.innerHTML = "See catalog";
        textocuenta.innerHTML = "Have you an account? log in here";
        btniniciar.innerHTML = "Log in";
        btnregistrate.innerHTML = "I want to register by another means";
        tituloslider1.innerHTML = "slide 1";
        parrafoslider1.innerHTML = "Lorem ipsum dolor sit amet consectetur.";
        tituloslider2.innerHTML = "slide 2";
        parrafoslider2.innerHTML = "Lorem ipsum dolor sit amet consectetur.";
        tituloslider3.innerHTML = "slide 3";
        parrafoslider3.innerHTML = "Lorem ipsum dolor sit amet consectetur.";
        titulodesarrollo.innerHTML = "Development";
        tituloformula.innerHTML = "Formula";
        list1.innerHTML = "With natural extracts";
        list2.innerHTML = "Not animal tested";
        list3.innerHTML = "Vegan";
        list4innerHTML = "No sulfates";
        list5.innerHTML = "Without parabens";
        list6.innerHTML = "Without salt";
        icono1.innerHTML = "Delivery Time Guarantee";
        icono2.innerHTML = "Versatility in the desired quantities";
        icono3.innerHTML = "Product performance guarantee";
        icono4.innerHTML = "Product performance guarantee";		
  }
}
